from .prompts.email_agent_prompt import EMAIL_AGENT_DESCRIPTION_AS_TOOL
from .prompts.orchestrator_agent_prompt import AGENT_ORCHESTRATOR_PROMPT
from .prompts.summarizer_agent_prompt import SUMMARIZER_AGENT_DESCRIPTION_AS_TOOL
from .prompts.translator_agent_prompt import TRANSLATOR_AGENT_DESCRIPTION_AS_TOOL